version: "3"

services:
  localstack:
    image: localstack/localstack:3.1
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=sns,sqs,s3,lambda,dynamodb,kinesis,kms
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CORS_HANDLERS=1
      - SKIP_CORS_PREFLIGHT=1
      - CORS_ALLOW_ORIGIN=*
      - CORS_EXPOSE_HEADERS=*
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - EXTRA_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,HEAD,OPTIONS
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack:/etc/localstack/init/ready.d
    networks:
      - dev

networks:
  dev:
